name: Shuttle Deploy

on:
  push:
    branches:
      - shuttle
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@v2
        with:
          shuttle-api-key: ${{ secrets.SHUTTLE_API_KEY }}
          project-id: proj_01JB8410KFMGSJZT1X49F4WP1F
          extra-args: --allow-dirty --debug
          secrets: |
            DISCORD_TOKEN = '${{ secrets.DISCORD_TOKEN }}'